### ISSUE TITLE
Development dependency in the main `require` block in composer.json

### ISSUE THREAD

**Issue by alexandrmazur96** [spatie/flysystem-google-cloud-storage#3]
Hi! 

Let me say that your packages are fantastic, and let me focus on business logic without spending time developing structural, service code.

However, is there any reason this package contains a `mockery/mockery` dependency in the main section in `composer.json`:
https://github.com/spatie/flysystem-google-cloud-storage/blob/13299332ae3701d11d9465b637c0b793efd1f986/composer.json#L21

This was added here - https://github.com/spatie/flysystem-google-cloud-storage/commit/05fb706d7b3430227daaf35e96ed042f13c418f7

Maybe moving it under the `require-dev` section to avoid installing development dependencies in our production code is possible?

Here`s the pull request that fixes this issue - https://github.com/spatie/flysystem-google-cloud-storage/pull/2

P.S. Thanks for supporting Ukraine in this challenging time for us ❤️

**Comment by alexandrmazur96** [comment]
@AlexVanderbist hi! Did you have any chance to look at it?

**Comment by freekmurze** [comment]
Fixed!
